### ISSUE TITLE
reactCellRendererFactory does not work with react-redux, or react-router

### ISSUE THREAD

**Issue by tannerlinsley** [ceolter/ag-grid-react#18]
Since the `reactCellRendererFactory` is creating new react contexts for each cell, using react router components like `Link` (or anything else that relies on React-Redux's `context`) will not work.  Props get passed down like normal, but context is used heavily by react-router and redux.  Any idea on how to support this?

**Comment by ceolter** [comment]
Afraid not. My react knowledge is very limited, I just learnt barely enough
to write the ag-grid-react component.

**Comment by DanielNesbitt** [comment]
The unstable API method `ReactDOM.unstable_renderSubtreeIntoContainer(...)` is the one to use when you want to render through 'portals' and preserve the context. Ideally that fixes the issues with Redux and the React Router.

Although it's an unstable API the React core team seem to recognize the need for it and indicate it will stick around.

facebook/react#4706
facebook/react#6599

I'll try this out myself when we get our first ag-grid implementation up and running.

**Comment by jameswyse** [comment]
Yeah, using `renderSubtreeIntoContainer` would fix this and greatly improve the react integration. I used it to create my own `CellEditorFactory` so I could use my existing react form components and it works well 👍 

To confirm what @DanielNesbitt said above; Don't let the 'unstable' flag worry you. it's only marked that way because the API may change in the future and it's apparently used heavily by Facebook so unlikely to be removed in the near future!

**Comment by ceolter** [comment]
is that something i need to change inside the ag-grid-react project? or something for clients of ag-grid-react to be aware of?

**Comment by sjmatta** [comment]
@ceolter It's a change to be made in the ag-grid-react project- please see #32. Thanks!

**Comment by ceolter** [comment]
@sjmatta thanks for the update. i'll look at that PR now.
