### ISSUE TITLE
In select cellEditor, focus changed when 'Enter' key is pressed

### ISSUE THREAD

**Issue by FrominXu** [ceolter/ag-grid-react#36]
I created a custom cell editor as follow:

SelectEditor.prototype.init = function(params) {
    let localeId=params.localeId;
    this.eSelect=document.createElement('select');
    let _this=this;
    params.SelectionOptions.forEach(function(item) {
        var eOption = document.createElement("option");
        eOption.setAttribute("value", item[0]);
        eOption.setAttribute("key",item[0]);
        eOption.innerHTML = item[1][localeId];
        _this.eSelect.appendChild(eOption);
    });
    this.eSelect.value = params.value;
   ...}

As editing the cell,  when I press the 'Enter' key ,the focused cell will changes to first column & first row  if the selected option not changed.

And, when I use the provided cellEditors 'select',as the demo:
colDef.cellEditor = 'select';
colDef.cellEditorParams = {
    values: ['English', 'Spanish', 'French', 'Portuguese', '(other)']
}
this situation appears again.

**Comment by ceolter** [comment]
i tried reproducing this on the demo site - and it works. can you reproduce in a plunker? then i can take a look. i'm trying not to copy / paste code down from github issues as then it takes to long to look at an issue, i'm trying to get through 100 of them today!

however - on a side note - i would NOT use the 'select' - i would use 'richSelect' instead (if you are using ag-Grid-Enterprise) - i have found the browsers 'select' to behave weird when inside the grid, especially when you are using keyboard shortcuts. this is because there is no API to open a select. the build in keyboard navigation for selects is poor.

**Comment by ceolter** [comment]
ps - why did you raise this in ag-grid-react? nothing to do with react!!

**Comment by FrominXu** [comment]
thank you for your response. I tried this operation again after I update ag-grid to V6, and I found no issue this time. 
I will use 'richSelect' if it is necessary,thanks.
our company is considering using ag-grid(ag-Grid-Enterprise) as the grid controller in React component, and i'm testing the performance of it now.
