### ISSUE TITLE
setFloatingTopRowData without 'refreshView'

### ISSUE THREAD

**Issue by psumstr** [ceolter/ag-grid-react#46]
This issue is related to https://github.com/ceolter/ag-grid-react/issues/43#event-840030968

It appears that the only way to refresh the cells for a floatingTopRow is to set the data again via the API:
`api.setFloatingTopRowData`. The problem that I'm having is that this will also call `RowRenderer.refreshView` which will rip out all of the rows and recreate them, including the non floating rows. Is there a reason why all the grid rows need to be refreshed? Anyway to prevent this?

I'm using ag-grid 6.4.2

**Comment by ceolter** [comment]
the reason is time, this was the quickest way to get it all working.

one way to prevent this is, assuming you are not changing the number of floating rows, is to use the rowNode.setData(newData) function instead.
https://www.ag-grid.com/javascript-grid-refresh/

use getFloatingTopRow(index) and getFloatingBottomRow(index) to get the row nodes.
